[package]
name = "process_sniper"
version = "1.0.0"
edition = "2018"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
sysinfo = "0"
libc = "0"
toml = "0"
winapi = "0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

